openapi: 3.0.3
info:
  title: Sample Finsei API
  version: 1.0.0
  description: A minimal API example for Mintlify integration testing.

servers:
  - url: https://api.test.inside.altpay.uk
    description: Altpay Test API

paths:
  /ping:
    get:
      summary: Health check
      description: Returns pong.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: pong

  /user:
    post:
      summary: Create a user
      description: Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: john@example.com
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: usr_abc123
        '400':
          description: Invalid input